# -*- coding: utf-8 -*-
"""
Created on 2024-01-03 12:02:23
---------
@summary:
---------
@author: Frank
"""

from feapder import Item


class DoubanFeapderItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i douban_feapder
    """

    __table_name__ = "douban_feapder"

    def __init__(self, *args, **kwargs):
        self.detail_text = None
        self.detail_url = None
        # self.id = None
        self.score = None
        self.title = None
